codecov:
  notify:
    after_n_builds: 2

coverage:
  status:
    project:
      default:
        target: 85%

ignore:
  - "aliyun-net-sdk-core.Tests/" # ignore aliyun-net-sdk-core.Tests

flags:
  unittest:
    # only test unittests
    paths:
      - aliyun-net-sdk-core.Tests/
  featuretest:
    # only test featuretest
    paths:
      - aliyun-net-feature-test/
